### ISSUE TITLE
Bug:"CuPy is not installed!", even I have installed cupy-cuda12x with spikingjelly 0.0.0.0.14.

### ISSUE THREAD

**Issue by yuchenweng-private** [fangwei123456/spikingjelly#459]
# **Read before creating a new issue**

- Users who want to use SpikingJelly should first be familiar with the usage of PyTorch. 
- If you do not know much about PyTorch, we recommend that the user can learn the [basic tutorials of PyTorch](https://pytorch.org/tutorials/).
- Do not ask for help with the basic conception of PyTorch/Machine Learning but not related to SpikingJelly. For these questions, please refer to Google or [PyTorch Forums](https://discuss.pytorch.org/).

**For faster response**

You can @ the corresponding developers for your issue. Here is the division:

| Features                         | Developers                                                   |
| -------------------------------- | ------------------------------------------------------------ |
| Neurons and Surrogate Functions  | [fangwei123456](https://github.com/fangwei123456)<br />[Yanqi-Chen](https://github.com/Yanqi-Chen) |
| CUDA Acceleration                | [fangwei123456](https://github.com/fangwei123456)<br />[Yanqi-Chen](https://github.com/Yanqi-Chen) |
| Reinforcement Learning           | [lucifer2859](https://github.com/lucifer2859)                |
| ANN to SNN Conversion            | [DingJianhao](https://github.com/DingJianhao)<br />[Lyu6PosHao](https://github.com/Lyu6PosHao) |
| Biological Learning (e.g., STDP) | [AllenYolk](https://github.com/AllenYolk)                    |
| Others                           | [Grasshlw](https://github.com/Grasshlw)<br />[lucifer2859](https://github.com/lucifer2859)<br />[AllenYolk](https://github.com/AllenYolk)<br />[Lyu6PosHao](https://github.com/Lyu6PosHao)<br />[DingJianhao](https://github.com/DingJianhao)<br />[Yanqi-Chen](https://github.com/Yanqi-Chen)<br />[fangwei123456](https://github.com/fangwei123456) |

We are glad to add new developers who are volunteering to help solve issues to the above table.

**Issue type**

- [x] Bug Report
- [ ] Feature Request
- [ ] Help wanted
- [ ] Other

**SpikingJelly version**

`0.0.0.0.14`

**Description**

...

**Minimal code to reproduce the error/bug**

```python
import spikingjelly
# ...
AssertionError: CuPy is not installed! You can install it from "https://github.com/cupy/cupy".
I have already tried to rebuild the whole environment with torch version 1.8.0 with cuda 11.1, but when I tried to build a MultiStepLIFNode with cupy backend, it still shows that I have not installed cupy.

**Comment by yuchenweng-private** [comment]
![image](https://github.com/fangwei123456/spikingjelly/assets/90203275/95a1ffb8-53bb-4578-88f7-0102188adde9)

**Comment by fangwei123456** [comment]
Hi, please install SpikingJelly from GitHub and check if it solves this problem.

**Comment by yuchenwengwyc** [comment]
Thanks, Dr, Fang. Finally, after I install the master version from github, it works with module activation_based.neuron LIFNode, and it is so wired that then I reinstall the old version, everything is good also with MultiStepLIFneuron.

**Comment by QiWang233** [comment]
# Issue type

- [ ] Help wanted 

# Description

I have already tried to rebuild the whole environment with torch version 1.13.0 with cuda 11.6, but when I tried to build a MultiStepLIFNode with cupy backend, it still shows that I have not installed cupy.

# Conda list
![微信图片_20240126191539](https://github.com/fangwei123456/spikingjelly/assets/59739521/dc383753-7187-4b0b-8d5f-d0fb5b0f4c08)

# Code
![微信图片_20240126191642](https://github.com/fangwei123456/spikingjelly/assets/59739521/264ebc5a-7206-4c7d-a2a4-7c18f49c9b83)
 
# Error
![微信图片_20240126185610](https://github.com/fangwei123456/spikingjelly/assets/59739521/da0dc469-41ed-478c-bbdd-d73fae9d0d55)

# Version  NVIDIA GeForce RTX 4090
![微信图片_20240126191753](https://github.com/fangwei123456/spikingjelly/assets/59739521/71a9a774-1629-4bc8-8a6e-643d0826b894)


1. "import cupy" is fine.
2. "change to the latest spikingjelly" doesnot work.
I had tried everything I can do, but it did not work, my god.

**Comment by fangwei123456** [comment]
@QiWang233 Hi, you can set logging level as DEBUG (https://docs.python.org/3/library/logging.html#logging.DEBUG) and check the outputs.

Meanwhile, you can also try to install the latest version from GitHub. Note that the `MultiStepLIFNode` is removed in the latest version. You can use `LIFNode` with `step_mode = 'm'`.

**Comment by QiWang233** [comment]
thanks for your reply! After changing the logging.debug and installing the latest version, I get questions below.
It can be seen that it is because of the lack of "lava" , so I wonder how can I install the "lava" correctly.

![image](https://github.com/fangwei123456/spikingjelly/assets/59739521/3bc705ae-e447-4bfa-9004-241fc7f6d123)

**Comment by fangwei123456** [comment]
Hi, lava is not easy to be installed... I suggest that you can change the source codes to avoid this problem (just ignore lava). Or you can install the latest version (we have fixed this problem).

**Comment by QiWang233** [comment]
Thanks for your patience！This is very important to me. But after changing to the lastest version 0.0.0.0.15，still the same problem.
```
import torch
import logging
logging.basicConfig(level=logging.DEBUG,
format='%(asctime)s - %(filename)s[line:%(lineno)d] - %(levelname)s: %(message)s')

try:
    import cupy
except BaseException as e:
    cupy = None

assert cupy is not None

print(cupy)
import spikingjelly
print(spikingjelly)
from spikingjelly.activation_based import neuron


lif = neuron.LIFNode(step_mode='m', backend='cupy').to('cuda:3')
x = torch.randn(10, 3, 224, 224).to('cuda:3')
out = lif(x)
print(out.shape)
```
---
![image](https://github.com/fangwei123456/spikingjelly/assets/59739521/2cacbc8d-ba3d-47e9-9341-ea5cbce931f1)

I do not know why...

**Comment by fangwei123456** [comment]
Set device as `cuda:0` and try again?

**Comment by QiWang233** [comment]
Sorry, it does not work...it is so weird.

**Comment by QiWang233** [comment]
Thank you! After changing to a device with 3090(4090->3090), it is solved. Hope my experience can help the other! But I still do not know why 4090 have problem, maybe it is related to the "High Version".

**Comment by sertreet** [comment]
I have also encountered the same problem and have been struggling for two days...
This is the log:
INFO:root:spikingjelly.clock_driven.lava_exchange: No module named 'lava.lib'
INFO:root:spikingjelly.clock_driven.neuron: No module named 'tensorboard'
INFO:root:spikingjelly.clock_driven.neuron: No module named 'lava.lib'
Then I installed Lava and TensorBoard and used them normally, although the logs still showed:
INFO:root:spikingjelly.clock_driven.lava_exchange: No module named 'lava.lib'
INFO:root:spikingjelly.clock_driven.neuron: No module named 'lava.lib'
But it no longer affects its use

**Comment by Da1sypetals** [comment]
This is probably due to you have not installed tensorboard. It is quite strange that pip does not resolve this dependency, but I got into the source code and found this log printed:
```
spikingjelly.clock_driven.neuron: No module named 'tensorboard'.
```
run `pip install tensorboard` solves the problem.

**Comment by Krisnon** [comment]
> This is probably due to you have not installed tensorboard. It is quite strange that pip does not resolve this dependency, but I got into the source code and found this log printed:
> 
> ```
> spikingjelly.clock_driven.neuron: No module named 'tensorboard'.
> ```
> 
> run `pip install tensorboard` solves the problem.

It works. The issue occurs in the file `/spikingjelly/clock_driven/neuron.py`:
```
try:
    import cupy
    from . import neuron_kernel, cu_kernel_opt
except BaseException as e:
    logging.info(f'spikingjelly.clock_driven.neuron: {e}')
    cupy = None
    neuron_kernel = None
    cu_kernel_opt = None
```
The root cause of the issue lies in `/spikingjelly/clock_driven/cu_kernel_opt.py`, where it attempts to import `tensorboard`. If this import fails, it triggers the exception handled in the above block, resulting in the "CuPy is not installed." problem.

**Comment by AllenYolk** [comment]
"CuPy is not installed!" 报错通常是因为你装的是 PyPI 上的 `0.0.0.0.14`，那个版本没有正确识别系统级 `cupy` 包。

修复办法：**从 GitHub master 安装**（issue 中 @yuchenwengwyc 已确认 master 安装后问题消失）：

```shell
git clone https://github.com/fangwei123456/spikingjelly.git
cd spikingjelly
pip install -e .
# 或者同时装上 cupy
pip install -e ".[cupy12]"   # CUDA 12.x
# pip install -e ".[cupy11]" # CUDA 11.x
```

如果你在 `QiWang233` 提到的 "3090 上才能跑、4090 上跑不了" 那种情况，可以参考 issue 评论——基本上是 `cupy-cuda12x` 与 GPU compute capability 的兼容问题，建议对照 nvcc / cupy 文档处理。

参考：
- #638（同类 OpenI 镜像说明）
- SpikingJelly 安装：https://spikingjelly.readthedocs.io/en/latest/getting_started/0_install.html

**Comment by AllenYolk** [comment]
"CuPy is not installed!" usually means you installed the PyPI `0.0.0.0.14`, which can't detect a system-installed `cupy` properly.

Fix: **install from GitHub master** (issue thread shows @yuchenwengwyc confirmed the master install works):

```shell
git clone https://github.com/fangwei123456/spikingjelly.git
cd spikingjelly
pip install -e .
# or install with cupy extras
pip install -e ".[cupy12]"   # CUDA 12.x
# pip install -e ".[cupy11]" # CUDA 11.x
```

For the "3090 works but 4090 doesn't" symptom that @QiWang233 reported, that's almost certainly a `cupy-cuda12x` / GPU compute-capability compatibility issue — check nvcc / cupy version compatibility.

References:
- #638 (related OpenI mirror note)
- Install docs: https://spikingjelly.readthedocs.io/en/latest/getting_started/0_install.html
